on:
  pull_request:
    branches:
      - main

# Cancel previously running workflows
concurrency:
  group: {{{{raw}}}}ci-${{ github.ref }}{{{{/raw}}}}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust (nightly)
        uses: dtolnay/rust-toolchain@nightly
        id: rust-toolchain
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          {{{{raw}}}}key: ${{ runner.os }}-cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}{{{{/raw}}}}

      - name: Run tests
        run: cargo test --locked

      - name: Run linting
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check formatting
        run: cargo fmt --all -- --check

